<?php

namespace AppBundle\Repository;

/**
 * JugadaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JugadaRepository extends \Doctrine\ORM\EntityRepository
{
}
