<?php

namespace AppBundle\Repository;

/**
 * PartidaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartidaRepository extends \Doctrine\ORM\EntityRepository
{
}
