<?php

namespace AppBundle\Repository;

/**
 * RestriccionesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RestriccionesRepository extends \Doctrine\ORM\EntityRepository
{
}
