color_index:
    path:     /
    defaults: { _controller: "AppBundle:Color:index" }
    methods:  GET

color_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Color:show" }
    methods:  GET

color_new:
    path:     /new
    defaults: { _controller: "AppBundle:Color:new" }
    methods:  [GET, POST]

color_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Color:edit" }
    methods:  [GET, POST]

color_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Color:delete" }
    methods:  DELETE
