jugada_index:
    path:     /
    defaults: { _controller: "AppBundle:Jugada:index" }
    methods:  GET

jugada_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Jugada:show" }
    methods:  GET

jugada_new:
    path:     /new
    defaults: { _controller: "AppBundle:Jugada:new" }
    methods:  [GET, POST]

jugada_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Jugada:edit" }
    methods:  [GET, POST]

jugada_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Jugada:delete" }
    methods:  DELETE
