partida_index:
    path:     /
    defaults: { _controller: "AppBundle:Partida:index" }
    methods:  GET

partida_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Partida:show" }
    methods:  GET

partida_new:
    path:     /new
    defaults: { _controller: "AppBundle:Partida:new" }
    methods:  [GET, POST]

partida_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Partida:edit" }
    methods:  [GET, POST]

partida_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Partida:delete" }
    methods:  DELETE
