restricciones_index:
    path:     /
    defaults: { _controller: "AppBundle:Restricciones:index" }
    methods:  GET

restricciones_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Restricciones:show" }
    methods:  GET

restricciones_new:
    path:     /new
    defaults: { _controller: "AppBundle:Restricciones:new" }
    methods:  [GET, POST]

restricciones_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Restricciones:edit" }
    methods:  [GET, POST]

restricciones_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Restricciones:delete" }
    methods:  DELETE
